.TH PYBRIDGE 6 "5 September 2006" "" ""

.SH NAME
PyBridge \- a free online bridge game.

.SH SYNOPSIS
.B pybridge

.SH DESCRIPTION
\fBpybridge\fR is a graphical interface for playing the card game of (contract) bridge over the Internet or a local network.

To actually use \fBpybridge\fR, you need to connect to a PyBridge game server. You may run a game server yourself (see \fBpybridge-server\fR) or connect to a public server. A list of public servers, along with other information, can be found at \fIhttp://pybridge.sourceforge.net/\fR.

.SH OPTIONS
\fBpybridge\fR accepts no options.

.SH SEE ALSO
\fBpybridge-server\fR(6)

.SH AUTHOR
This manual page was written by Michael Banks <michael@banksie.co.uk>.

.SH BUGS
Plenty. Please report any bugs you find.
