.TH PYBRIDGE-SERVER 6 "5 September 2006" "" ""

.SH NAME
PyBridge Server \- a game server for PyBridge.

.SH SYNOPSIS
\fBpybridge-server\fR [options]

.SH DESCRIPTION
\fBpybridge-server\fR is a game server for PyBridge. It accepts incoming network connections from \fBpybridge\fR clients.

For more information, visit \fIhttp://pybridge.sourceforge.net/\fR.

.SH OPTIONS

.TP
\fB\-h\fR, \fB--help\fR
Print help message and exit.

.TP
\fB\-p\fR \fIportnum\fR, \fB--port\fB \fIportnum\fR
Listen for incoming connections on port \fIportnum\fR. (The default port is 5040.)

.TP
.BR \fB\-v\fR, \fB--version\fR
Print version information and exit.

.SH SEE ALSO
\fBpybridge\fR(6)

.SH AUTHOR
This manual page was written by Michael Banks <michael@banksie.co.uk>.

.SH BUGS
Plenty. Please report any bugs you find.
