#!/usr/bin/env python

# Use psyco for speed-up
try :
	import psyco
	psyco.profile()
except ImportError :
	pass

# Package source configuration
import pybridge.gui

# Let's go
if __name__ == "__main__" :
	app = pybridge.gui.app()
	app.run()

